# 1.Import necessary library

In [1]:
import pandas as pd

# 2.Data Collection

In [2]:
claimants_Data = pd.read_csv("claimants.csv")
claimants_Data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

# 3.Data understanding

In [4]:
claimants_Data.shape

(1340, 7)

In [5]:
claimants_Data.isnull().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

# 4.Data Preparation

### 4.1 Data Cleaning

In [15]:
claimants_Data.dropna(inplace=True)
claimants_Data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1334    34104         1     1.0       1.0       0.0    16.0   0.060
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1096 rows x 7 columns]

In [9]:
claimants_Data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

### 4.2 Separating input and output

In [16]:
x = claimants_Data.drop(labels=["CASENUM","ATTORNEY"], axis = "columns")
x

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [17]:
y=claimants_Data["ATTORNEY"]
y

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1096, dtype: int64

# 5.Model Building

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_auc_score,roc_curve

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20,shuffle=True)
X_train, X_test, y_train, y_test

(      CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
 618      0.0       1.0       0.0    83.0  0.380
 464      0.0       1.0       0.0    30.0  0.500
 607      1.0       1.0       0.0     4.0  0.655
 580      1.0       1.0       0.0     8.0  6.047
 271      1.0       1.0       0.0     6.0  4.300
 ...      ...       ...       ...     ...    ...
 1308     1.0       1.0       0.0    43.0  5.434
 1330     0.0       1.0       0.0    33.0  6.817
 225      0.0       1.0       0.0    19.0  1.644
 496      1.0       1.0       0.0     9.0  1.645
 1254     0.0       1.0       0.0    37.0  4.318

 [1072 rows x 5 columns],
       CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
 1007     0.0       1.0       0.0     5.0  0.500
 1020     1.0       1.0       0.0    36.0  4.303
 1028     1.0       1.0       0.0    10.0  0.946
 901      1.0       1.0       0.0     9.0  0.405
 999      1.0       1.0       0.0    15.0  1.090
 ...      ...       ...       ...     ...    ...
 697      0.0       1.0       0.0     NaN  0.400
 1190     0.0       1.0       0.0    48.0  3.549
 140      1.0       1.0       0.0     7.0  0.655
 261      0.0       1.0       0.0    30.0  0.118
 1313     1.0       1.0       0.0     7.0  0.986

 [268 rows x 5 columns],
 618     1
 464     1
 607     0
 580     0
 271     0
        ..
 1308    0
 1330    1
 225     0
 496     0
 1254    0
 Name: ATTORNEY, Length: 1072, dtype: int64,
 1007    1
 1020    0
 1028    1
 901     1
 999     1
        ..
 697     1
 1190    0
 140     0
 261     1
 1313    1
 Name: ATTORNEY, Length: 268, dtype: int64)

In [19]:
Logistic_model = LogisticRegression()

In [8]:
from sklearn.model_selection import KFold,cross_val_score,LeaveOneOut

In [9]:
kfold = KFold(n_splits=5, shuffle=True, random_state=22)

In [20]:
cross_val_Score = cross_val_score(estimator = Logistic_model,X=x, y=y,cv = kfold )

In [21]:
print(cross_val_Score)
print("Overall Accuracy:", cross_val_Score.mean().round(2))
print("Overall Std.Deviation:", cross_val_Score.std().round(2))

[0.68636364 0.7260274  0.69863014 0.69406393 0.71689498]
Overall Accuracy: 0.7
Overall Std.Deviation: 0.01

# 6.Model Training

In [51]:
Logistic_model.fit(X_train,y_train)

LogisticRegression()

In [1]:
from sklearn.tree import DecisionTreeClassifier

In [2]:
dt_model = DecisionTreeClassifier()

# 7.Model Testing

In [42]:
y_pred_train = Logistic_model.predict(X_train)

In [43]:
y_pred_test = Logistic_model.predict(X_test)

# 8.Modeling Evalution

In [46]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_auc_score,roc_curve

In [52]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.55      0.51      0.53       460
           1       0.49      0.53      0.51       416

    accuracy                           0.52       876
   macro avg       0.52      0.52      0.52       876
weighted avg       0.52      0.52      0.52       876

In [53]:
print(confusion_matrix(y_train,y_pred_train))

[[233 227]
 [194 222]]

In [44]:
accuracy_score(y_train,y_pred_train)

0.7031963470319634

In [45]:
accuracy_score(y_test,y_pred_test)

0.7227272727272728

In [ ]:
roc_curve(

# 9.Model deployment

In [31]:
from pickle import dump
dump(Logistic_model,open("claimants_Practice.pkl","wb"))